# Generated by Django 5.1.14 on 2025-11-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='houses.house'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='devices.componenttype'),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='allowed_component_types',
            field=models.ManyToManyField(blank=True, to='devices.componenttype'),
        ),
        migrations.AddField(
            model_name='microcontroller',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microcontrollers', to='houses.house'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['house', 'status'], name='component_house_i_941fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['mac_address'], name='component_mac_add_2338c5_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['device_id'], name='component_device__84a1db_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['last_seen'], name='component_last_se_de340c_idx'),
        ),
        migrations.AddIndex(
            model_name='microcontroller',
            index=models.Index(fields=['house', 'status'], name='microcontro_house_i_67074a_idx'),
        ),
        migrations.AddIndex(
            model_name='microcontroller',
            index=models.Index(fields=['mac_address'], name='microcontro_mac_add_10d2e0_idx'),
        ),
        migrations.AddIndex(
            model_name='microcontroller',
            index=models.Index(fields=['last_heartbeat'], name='microcontro_last_he_24a841_idx'),
        ),
    ]
