# Generated by Django 5.1.14 on 2025-12-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcontroller',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, help_text='Leave empty to auto-generate', max_length=100, null=True, unique=True),
        ),
    ]
