# Generated by Django 5.1.14 on 2025-12-23 15:44

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_initial'),
        ('devices', '0003_alter_microcontroller_api_key'),
        ('houses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='execution_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='memory_usage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='request_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='source',
            field=models.CharField(choices=[('mobile_app', 'Mobile App'), ('web_app', 'Web App'), ('api', 'API'), ('microcontroller', 'Microcontroller'), ('physical_switch', 'Physical Switch'), ('automation', 'Automation'), ('admin', 'Admin Panel'), ('system', 'System')], default='api', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_parameters',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_result',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='devices.component'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='log_level',
            field=models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('security', 'Security')], default='info', max_length=10),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['source', 'created_at'], name='activity_lo_source_f36eb1_idx'),
        ),
    ]
