# Generated by Django 5.1.14 on 2026-04-30 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_initial'),
        ('devices', '0002_initial'),
        ('houses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='app_version',
            field=models.CharField(blank=True, help_text='Mobile app version (e.g., 1.2.3)', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='device_platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web Browser'), ('esp32', 'ESP32 Microcontroller'), ('api', 'API Call'), ('unknown', 'Unknown')], default='unknown', help_text='Platform the action came from', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='duration_ms',
            field=models.IntegerField(blank=True, help_text='Action duration in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='firmware_version',
            field=models.CharField(blank=True, help_text='ESP32 firmware version', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='household_member_id',
            field=models.UUIDField(blank=True, help_text='Which household member performed the action', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='is_billable',
            field=models.BooleanField(default=True, help_text='Whether this action counts toward billing/usage limits'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude of the user/device', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude of the user/device', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique request ID for correlating related log entries', max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='User session ID for tracking user journey', max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='subscription_tier',
            field=models.CharField(blank=True, help_text="User's subscription plan (free, basic, premium, enterprise)", max_length=20),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['session_id', 'created_at'], name='activity_lo_session_2db2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['request_id'], name='activity_lo_request_3438dc_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['device_platform', 'created_at'], name='activity_lo_device__60c827_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['subscription_tier', 'created_at'], name='activity_lo_subscri_1424db_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['is_billable', 'created_at'], name='activity_lo_is_bill_1b6d33_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['session_id', 'created_at'], name='security_ev_session_98b620_idx'),
        ),
    ]
