# Generated by Django 5.1.14 on 2026-04-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activitylog_app_version_activitylog_device_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='User session ID for tracking user journey', max_length=100),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
