# Generated by Django 5.1.14 on 2026-04-29 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activitylog_execution_time_activitylog_memory_usage_and_more'),
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='houses.house'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='houses.house'),
        ),
    ]
