# Generated by Django 5.1.14 on 2025-11-13 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('gps_coordinates', models.CharField(blank=True, max_length=100)),
                ('house_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'db_table': 'house',
                'indexes': [models.Index(fields=['house_code', 'is_active'], name='house_house_c_36a4c2_idx'), models.Index(fields=['created_at'], name='house_created_5f4ff1_idx')],
            },
        ),
        migrations.CreateModel(
            name='HouseUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('resident', 'Resident'), ('guest', 'Guest')], default='resident', max_length=20)),
                ('can_control_devices', models.BooleanField(default=True)),
                ('can_invite_users', models.BooleanField(default=False)),
                ('can_manage_house', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_users', to='houses.house')),
            ],
            options={
                'verbose_name': 'House User',
                'verbose_name_plural': 'House Users',
                'db_table': 'house_user',
            },
        ),
    ]
