# Generated by Django 5.1.14 on 2025-11-13 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='houseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='houseuser',
            index=models.Index(fields=['user', 'house'], name='house_user_user_id_d0802a_idx'),
        ),
        migrations.AddIndex(
            model_name='houseuser',
            index=models.Index(fields=['access_level'], name='house_user_access__5bf38f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='houseuser',
            unique_together={('user', 'house')},
        ),
    ]
