# Generated by Django 5.1.14 on 2025-11-17 07:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
        ('houses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('schedule', 'Schedule'), ('device_state', 'Device State Change'), ('sensor_value', 'Sensor Value'), ('manual', 'Manual')], max_length=20)),
                ('trigger_conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('max_executions_per_hour', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='houses.house')),
            ],
            options={
                'verbose_name': 'Automation Rule',
                'verbose_name_plural': 'Automation Rules',
                'db_table': 'automation_rule',
                'indexes': [models.Index(fields=['house', 'is_active'], name='automation__house_i_106cba_idx'), models.Index(fields=['trigger_type', 'is_active'], name='automation__trigger_121367_idx')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('action_parameters', models.JSONField(default=dict)),
                ('scheduled_time', models.TimeField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('next_trigger', models.DateTimeField(blank=True, null=True)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('max_duration_minutes', models.IntegerField(default=120, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='devices.actiontype')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='devices.component')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='houses.house')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedule',
                'indexes': [models.Index(fields=['house', 'is_active'], name='schedule_house_i_96b1fa_idx'), models.Index(fields=['component', 'is_active'], name='schedule_compone_9dd9ac_idx'), models.Index(fields=['next_trigger'], name='schedule_next_tr_28d646_idx'), models.Index(fields=['is_active', 'next_trigger'], name='schedule_is_acti_166263_idx')],
            },
        ),
    ]
