# Generated by Django 5.1.14 on 2026-04-29 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0002_initial'),
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='houses.house'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['house', 'is_active'], name='automation__house_i_106cba_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['trigger_type', 'is_active'], name='automation__trigger_121367_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['house', 'is_active'], name='schedule_house_i_96b1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['component', 'is_active'], name='schedule_compone_9dd9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['next_trigger'], name='schedule_next_tr_28d646_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['is_active', 'next_trigger'], name='schedule_is_acti_166263_idx'),
        ),
    ]
